### PR TITLE
add torchscript convert script

### PR DESCRIPTION
**Pull request by Sanster**
```bash
PYTHONPATH=`pwd` python3 bin/to_jit.py model.path=$(pwd)/big-lama +save_path=/path/to/save/big-lama.jit
```

### CODE REVIEW

**Comment by ternaus** [comment]
Hi. Any updates on this PR? Being able to jit models would be ultra-useful.

**Comment by Sanster** [comment]
Rebased and tested on latest main branch

**Review by windj007 — APPROVED** [review]

**Review by alialmrhbi7 — COMMENTED** [review]
https://github.com/saic-mdal/lama/commit/ede702b19b027ad2c0380419b2b71a90fe90a14f

**Comment by benjaminkech** [comment]
@Sanster, can you explain how you converted the model? When running the ```PYTHONPATH=`pwd` python3 bin/to_jit.py model.path=$(pwd)/big-lama +save_path=/path/to/save/big-lama.jit``` command, a RuntimeError occurs with the message: "DefaultInpaintingTrainingModule is not attached to a 'Trainer'."

**Comment by 123scarecrow** [comment]
> @Sanster, can you explain how you converted the model? When running the `` PYTHONPATH=`pwd` python3 bin/to_jit.py model.path=$(pwd)/big-lama +save_path=/path/to/save/big-lama.jit `` command, a RuntimeError occurs with the message: "DefaultInpaintingTrainingModule is not attached to a 'Trainer'."

Hello, have you solved this problem? I seem to have encountered the same error.

**Pull request merged**
